// Code generated by goctl. DO NOT EDIT.
// Source: article.proto

package article

import (
	"context"

	"zh-go-zero/application/article/rpc/service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticleDeleteRequest   = service.ArticleDeleteRequest
	ArticleDeleteResponse  = service.ArticleDeleteResponse
	ArticleDetailRequest   = service.ArticleDetailRequest
	ArticleDetailResponse  = service.ArticleDetailResponse
	ArticleItem            = service.ArticleItem
	ArticlesRequest        = service.ArticlesRequest
	ArticlesResponse       = service.ArticlesResponse
	PublishArticleRequest  = service.PublishArticleRequest
	PublishArticleResponse = service.PublishArticleResponse

	Article interface {
		PublishArticle(ctx context.Context, in *PublishArticleRequest, opts ...grpc.CallOption) (*PublishArticleResponse, error)
		Articles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error)
		ArticleDelete(ctx context.Context, in *ArticleDeleteRequest, opts ...grpc.CallOption) (*ArticleDeleteResponse, error)
		ArticleDetail(ctx context.Context, in *ArticleDetailRequest, opts ...grpc.CallOption) (*ArticleDetailResponse, error)
	}

	defaultArticle struct {
		cli zrpc.Client
	}
)

func NewArticle(cli zrpc.Client) Article {
	return &defaultArticle{
		cli: cli,
	}
}

func (m *defaultArticle) PublishArticle(ctx context.Context, in *PublishArticleRequest, opts ...grpc.CallOption) (*PublishArticleResponse, error) {
	client := service.NewArticleClient(m.cli.Conn())
	return client.PublishArticle(ctx, in, opts...)
}

func (m *defaultArticle) Articles(ctx context.Context, in *ArticlesRequest, opts ...grpc.CallOption) (*ArticlesResponse, error) {
	client := service.NewArticleClient(m.cli.Conn())
	return client.Articles(ctx, in, opts...)
}

func (m *defaultArticle) ArticleDelete(ctx context.Context, in *ArticleDeleteRequest, opts ...grpc.CallOption) (*ArticleDeleteResponse, error) {
	client := service.NewArticleClient(m.cli.Conn())
	return client.ArticleDelete(ctx, in, opts...)
}

func (m *defaultArticle) ArticleDetail(ctx context.Context, in *ArticleDetailRequest, opts ...grpc.CallOption) (*ArticleDetailResponse, error) {
	client := service.NewArticleClient(m.cli.Conn())
	return client.ArticleDetail(ctx, in, opts...)
}
