// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package server

import (
	"context"

	"zh-go-zero/application/like/rpc/internal/logic"
	"zh-go-zero/application/like/rpc/internal/svc"
	"zh-go-zero/application/like/rpc/service"
)

type LikeServer struct {
	svcCtx *svc.ServiceContext
	service.UnimplementedLikeServer
}

func NewLikeServer(svcCtx *svc.ServiceContext) *LikeServer {
	return &LikeServer{
		svcCtx: svcCtx,
	}
}

func (s *LikeServer) ThumbUp(ctx context.Context, in *service.ThumbUpRequest) (*service.ThumbUpResponse, error) {
	l := logic.NewThumbUpLogic(ctx, s.svcCtx)
	return l.ThumbUp(in)
}

func (s *LikeServer) IsThumbUp(ctx context.Context, in *service.IsThumbUpRequest) (*service.IsThumbUpResponse, error) {
	l := logic.NewIsThumbUpLogic(ctx, s.svcCtx)
	return l.IsThumbUp(in)
}
