// Code generated by goctl. DO NOT EDIT.
// Source: like.proto

package like

import (
	"context"

	"zh-go-zero/application/like/rpc/service"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IsThumbUpRequest  = service.IsThumbUpRequest
	IsThumbUpResponse = service.IsThumbUpResponse
	ThumbUpRequest    = service.ThumbUpRequest
	ThumbUpResponse   = service.ThumbUpResponse
	UserThumbUp       = service.UserThumbUp

	Like interface {
		ThumbUp(ctx context.Context, in *ThumbUpRequest, opts ...grpc.CallOption) (*ThumbUpResponse, error)
		IsThumbUp(ctx context.Context, in *IsThumbUpRequest, opts ...grpc.CallOption) (*IsThumbUpResponse, error)
	}

	defaultLike struct {
		cli zrpc.Client
	}
)

func NewLike(cli zrpc.Client) Like {
	return &defaultLike{
		cli: cli,
	}
}

func (m *defaultLike) ThumbUp(ctx context.Context, in *ThumbUpRequest, opts ...grpc.CallOption) (*ThumbUpResponse, error) {
	client := service.NewLikeClient(m.cli.Conn())
	return client.ThumbUp(ctx, in, opts...)
}

func (m *defaultLike) IsThumbUp(ctx context.Context, in *IsThumbUpRequest, opts ...grpc.CallOption) (*IsThumbUpResponse, error) {
	client := service.NewLikeClient(m.cli.Conn())
	return client.IsThumbUp(ctx, in, opts...)
}
